apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: backend
    context: backend
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - service.yaml
